<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New User - SignUp</name>
   <tag></tag>
   <elementGuidId>2238b53b-cb1e-444d-8970-8558157f8ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.back-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/form/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6cf41fb-3ce9-401c-b021-1c51348879c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-link</value>
      <webElementGuid>64d6ebf4-9f66-4dd5-94f8-0b23bac9331f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/register</value>
      <webElementGuid>18542523-1448-4283-a9a9-21aa2fc3d7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New User - SignUp</value>
      <webElementGuid>48be880a-b754-453c-abf8-6a42713b786d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;logon-container&quot;]/section[@class=&quot;form&quot;]/form[1]/a[@class=&quot;back-link&quot;]</value>
      <webElementGuid>3a55a365-fbe4-4393-9d61-e3900c13fbe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/form/a</value>
      <webElementGuid>3e697170-ac19-4e80-87c5-c9dd3bb85161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New User - SignUp')]</value>
      <webElementGuid>4de726ac-b8ed-473b-a19f-b55374338e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LogIn'])[2]/following::a[1]</value>
      <webElementGuid>530f653e-78ca-44ae-b840-68b955611c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LogIn'])[1]/following::a[1]</value>
      <webElementGuid>91a33cac-55ea-4d08-9931-85f8a78624b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New User - SignUp']/parent::*</value>
      <webElementGuid>2e3d75a4-d7ca-4d6f-9f3b-cdad690ef744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/register')]</value>
      <webElementGuid>df9463f8-666e-401d-92e1-c060c5aec1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>9fc22897-83ce-48be-bb1b-ae0a8a837b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/register' and (text() = 'New User - SignUp' or . = 'New User - SignUp')]</value>
      <webElementGuid>6482126e-b5a3-476b-a597-1e67a96a6fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
