<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>acctDetailsDescp</name>
   <tag></tag>
   <elementGuidId>1dec802c-9d02-4f60-97a3-088da6f50c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>549d4a91-a6c0-4e3e-b778-3618ae3d4e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID:986d6768NAME:TestNGO2EMAIL:testngo2@gmail.comWHATSAPP:1234567891CITY:BangloreCODE:KA</value>
      <webElementGuid>d157e13c-02aa-4015-86cc-2426c6220d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;profile-container&quot;]/ul[1]/li[1]</value>
      <webElementGuid>18a73fda-a4d9-4aa2-8dd6-0fa2e922585a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/ul/li</value>
      <webElementGuid>70339818-88cf-4246-930f-aa4baad09f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongs Details'])[1]/following::li[1]</value>
      <webElementGuid>d04920fc-8335-4390-b9df-b91c1e02e060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to home'])[1]/following::li[1]</value>
      <webElementGuid>a9161bf9-246b-4852-b78c-9b95c650169c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>6ef6b7b0-d359-4050-8d0a-d39ea1169ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ID:986d6768NAME:TestNGO2EMAIL:testngo2@gmail.comWHATSAPP:1234567891CITY:BangloreCODE:KA' or . = 'ID:986d6768NAME:TestNGO2EMAIL:testngo2@gmail.comWHATSAPP:1234567891CITY:BangloreCODE:KA')]</value>
      <webElementGuid>11c2c21f-71f3-43a3-a7f8-e1853af66ecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
