<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>userName</name>
   <tag></tag>
   <elementGuidId>e4b3847b-240c-4986-b0cc-ee939e77fedb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[value=&quot;SaiSindhuja&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li/strong[text()='NAME:']/following-sibling::p[position()=1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ad7a1a9-2be7-4ed8-a9e9-ecd759271cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SaiSindhuja</value>
      <webElementGuid>da32cb52-6e26-41ee-869a-2b8fd3901ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SaiSindhuja</value>
      <webElementGuid>1b5593ab-00b0-4af7-9d2a-5a2cd176f312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;new-incident-container&quot;]/div[@class=&quot;content&quot;]/form[1]/input[1]</value>
      <webElementGuid>c7a58c67-7d61-4c00-a00e-06ca7009218e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SaiSindhuja']</value>
      <webElementGuid>d87ddd7f-62ad-4a26-9cd2-7db50335afc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/input</value>
      <webElementGuid>18024630-6619-4469-88e2-545814c46e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e1c212a6-2bed-49bf-9f1f-503bc8b9e55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'SaiSindhuja']</value>
      <webElementGuid>b2a5c919-611b-4152-b841-2c81960594d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
